# Generated by Django 4.0.4 on 2022-05-31 06:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stageName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VideoArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicName', models.CharField(blank=True, max_length=50, null=True)),
                ('keyword', models.CharField(blank=True, max_length=50, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv', 'flac'])])),
                ('roleName', models.BooleanField(default=True, verbose_name='Is Caregiver Article ?')),
                ('categoryName', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='stageName', chained_model_field='stageName', on_delete=django.db.models.deletion.CASCADE, to='home.categories')),
                ('parentTopicName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.videoarticle')),
                ('stageName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.stage')),
            ],
        ),
        migrations.CreateModel(
            name='TextualArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicName', models.CharField(blank=True, max_length=50, null=True)),
                ('keyword', models.CharField(blank=True, max_length=50, null=True)),
                ('body', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('medlinePlusUrl', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('summary', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=50, null=True)),
                ('learnMoreUrl', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('roleName', models.BooleanField(default=False, verbose_name='Is Caregiver Article ?')),
                ('categoryName', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='stageName', chained_model_field='stageName', on_delete=django.db.models.deletion.CASCADE, to='home.categories')),
                ('parentTopicName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.textualarticle')),
                ('stageName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.stage')),
            ],
        ),
        migrations.AddField(
            model_name='categories',
            name='stageName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.stage'),
        ),
        migrations.CreateModel(
            name='AudioArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicName', models.CharField(blank=True, max_length=50, null=True)),
                ('keyword', models.CharField(blank=True, max_length=50, null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp3', 'webm', 'mkv', 'flac'])])),
                ('roleName', models.BooleanField(default=False, verbose_name='Is Caregiver Article ?')),
                ('categoryName', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='stageName', chained_model_field='stageName', on_delete=django.db.models.deletion.CASCADE, to='home.categories')),
                ('parentTopicName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.audioarticle')),
                ('stageName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.stage')),
            ],
        ),
    ]
