# Generated by Django 4.0.4 on 2022-06-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_audioarticle_categoryname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioarticle',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='audioarticle',
            name='uid',
            field=models.CharField(blank=True, default='9c482d55-7b4b-439c-8f0b-82db1c9ecd80', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='textualarticle',
            name='uid',
            field=models.CharField(blank=True, default='b7f66291-96b2-4b59-8891-1c78f54ce2b5', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='videoarticle',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='videoarticle',
            name='uid',
            field=models.CharField(blank=True, default='5f8e9020-fb31-4600-8955-f1ca13b3f559', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='textualarticle',
            name='summary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
