# Generated by Django 4.0.4 on 2022-06-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_audioarticle_uid_alter_textualarticle_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='categoryName',
            field=models.CharField(max_length=50, unique=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='stageName',
            field=models.CharField(max_length=50, unique=True, verbose_name='Stage Name'),
        ),
    ]
