# Generated by Django 4.0.4 on 2022-06-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_categories_categoryname_alter_stage_stagename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioarticle',
            name='keyword',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='textualarticle',
            name='keyword',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='videoarticle',
            name='keyword',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
