# Generated by Django 4.0.4 on 2022-06-13 10:36

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_audioarticle_keyword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioarticle',
            name='audio',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'flac']), home.models.file_size]),
        ),
        migrations.AlterField(
            model_name='audioarticle',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='audioarticle',
            name='keyword',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='audioarticle',
            name='stageName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.stage', verbose_name='Stage Name'),
        ),
        migrations.AlterField(
            model_name='audioarticle',
            name='topicName',
            field=models.CharField(default='', max_length=100, verbose_name='Topic Name'),
        ),
        migrations.AlterField(
            model_name='textualarticle',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
        migrations.AlterField(
            model_name='textualarticle',
            name='keyword',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='textualarticle',
            name='learnMoreUrl',
            field=models.URLField(blank=True, null=True, verbose_name='More URL'),
        ),
        migrations.AlterField(
            model_name='textualarticle',
            name='medlinePlusUrl',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Medline Plus URL'),
        ),
        migrations.AlterField(
            model_name='textualarticle',
            name='stageName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.stage', verbose_name='Stage Name'),
        ),
        migrations.AlterField(
            model_name='textualarticle',
            name='summary',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='textualarticle',
            name='topicName',
            field=models.CharField(default='', max_length=100, verbose_name='Topic Name'),
        ),
        migrations.AlterField(
            model_name='videoarticle',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='videoarticle',
            name='keyword',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='videoarticle',
            name='parentTopicName',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.videoarticle', verbose_name='Parent Topic Name'),
        ),
        migrations.AlterField(
            model_name='videoarticle',
            name='stageName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.stage', verbose_name='Stage Name'),
        ),
        migrations.AlterField(
            model_name='videoarticle',
            name='topicName',
            field=models.CharField(default='', max_length=100, verbose_name='Topic Name'),
        ),
        migrations.AlterField(
            model_name='videoarticle',
            name='video',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'MOV', 'avi', 'mkv', 'mp3']), home.models.file_size]),
        ),
    ]
