# Generated by Django 4.0.4 on 2022-06-19 10:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_audioarticle_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='imgSrc',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Img Src'),
        ),
        migrations.AddField(
            model_name='categories',
            name='tourContent',
            field=models.CharField(default='', max_length=50, verbose_name='Tour Content'),
        ),
        migrations.AddField(
            model_name='categories',
            name='tourKey',
            field=models.CharField(default='', max_length=50, verbose_name='Tour Key'),
        ),
        migrations.AddField(
            model_name='stage',
            name='tourContent',
            field=models.CharField(default='', max_length=50, verbose_name='Tour Content'),
        ),
        migrations.AddField(
            model_name='stage',
            name='tourKey',
            field=models.CharField(default='', max_length=50, verbose_name='Tour Key'),
        ),
        migrations.AlterField(
            model_name='audioarticle',
            name='audio',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'flac', 'M4A', 'aac']), home.models.file_size]),
        ),
        migrations.AlterField(
            model_name='audioarticle',
            name='keyword',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='textualarticle',
            name='keyword',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='textualarticle',
            name='summary',
            field=models.CharField(default='', max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='videoarticle',
            name='keyword',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='videoarticle',
            name='video',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'MOV', 'avi', 'mkv', 'wmv', 'avi']), home.models.file_size]),
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.CharField(default='', max_length=50, verbose_name='Top')),
                ('left', models.CharField(default='', max_length=50, verbose_name='Left')),
                ('categoryName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='style', to='home.categories', unique=True, verbose_name='Category Name')),
            ],
        ),
    ]
