# Generated by Django 4.0.4 on 2022-06-19 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_categories_imgsrc_categories_tourcontent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='stageName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='home.stage', verbose_name='Stage Name'),
        ),
    ]
