# Generated by Django 4.0.4 on 2022-06-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_categories_imgsrc_alter_categories_tourcontent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='iconImg',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='icon Img'),
        ),
    ]
