# Generated by Django 4.0.4 on 2022-06-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_audioarticle_audio_alter_videoarticle_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioarticle',
            name='audio',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='videoarticle',
            name='video',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=''),
        ),
    ]
