# Generated by Django 4.0.4 on 2022-06-21 06:15

import django.core.validators
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_audioarticle_audio_alter_videoarticle_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioarticle',
            name='audio',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp3', 'webm', 'mkv', 'flac']), home.models.file_size]),
        ),
        migrations.AlterField(
            model_name='videoarticle',
            name='video',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv', 'flac']), home.models.file_size]),
        ),
    ]
