# Generated by Django 4.0.4 on 2022-07-30 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_audioarticle_audio_alter_videoarticle_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioarticle',
            name='audio',
            field=models.FileField(default='', max_length=200, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'flac', 'wav'])], verbose_name="AUDIO (Max file size can be 500MB) & allowed format ('mp3','flac','wav')"),
        ),
        migrations.AlterField(
            model_name='videoarticle',
            name='video',
            field=models.FileField(default='', max_length=200, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv', 'flac'])], verbose_name="VIDEO (Max file size can be 500MB) & allowed format ('MOV','avi','mp4','webm','mkv','flac')"),
        ),
    ]
