# Generated by Django 3.2.16 on 2023-04-01 05:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_audioarticle_audio_alter_videoarticle_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoarticle',
            name='video',
            field=models.FileField(default='', max_length=200, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'mp4', 'webm', 'flac'])], verbose_name="VIDEO (Max file size can be 500MB) & allowed format ('MOV','mp4','webm','flac')"),
        ),
    ]
